### ISSUE TITLE
关于加入快捷键

### ISSUE THREAD

**Issue by Onlyn1ght** [imlinhanchao/fishpi-desktop#24]
跳跳大佬，可以加一个 呼出/隐藏 的快捷键吗

**Comment by imlinhanchao** [comment]
可以。周末更新。

**Comment by imlinhanchao** [comment]
1.2.1 已加入，可以进入设置界面，点击版本号后的按钮进行在线更新。

![image](https://user-images.githubusercontent.com/1502581/189568197-ed14f074-9997-49be-a580-dc1b4af9dd7e.png)
