### ISSUE TITLE
关于积分的问题

### ISSUE THREAD

**Issue by Onlyn1ght** [imlinhanchao/fishpi-desktop#25]
积分显示不正确
![image](https://user-images.githubusercontent.com/91249019/189016206-6566f9b4-b76d-43ef-b6ac-5b7807cbf3da.png)

Web端
![image](https://user-images.githubusercontent.com/91249019/189016254-1837c941-b53c-465e-b440-a5cd3776cd8e.png)

**Comment by imlinhanchao** [comment]
是個bug，周末修正。

**Comment by imlinhanchao** [comment]
1.2.1 已修正
