### ISSUE TITLE
版本更新问题

### ISSUE THREAD

**Issue by Onlyn1ght** [imlinhanchao/fishpi-desktop#26]
![image](https://user-images.githubusercontent.com/91249019/189784346-ff4036f8-33a7-4554-a61c-769938ee9bf5.png)
在客户端版本号点击更新出现了这个提示

**Comment by imlinhanchao** [comment]
已知問題，用的 GitHub 鏡像有問題。下版本修正。

**Comment by imlinhanchao** [comment]
已解决
