### ISSUE TITLE
长时间使用 私聊发送消息 显示两条

### ISSUE THREAD

**Issue by fghwett** [imlinhanchao/fishpi-desktop#27]
电脑休眠过 第二天早上发私聊消息 会显示发出去两条 实际还是只发了一条
![image](https://user-images.githubusercontent.com/38271480/192929308-5c275efb-477c-41f2-9ed3-a9db12feddce.png)

**Comment by imlinhanchao** [comment]
已解决

**Comment by fghwett** [comment]
跳跳大佬 YES
