### ISSUE TITLE
消息屏蔽设置后，聊天室变的很卡

### ISSUE THREAD

**Issue by KwdeTfpv** [imlinhanchao/fishpi-desktop#28]
系统：Windows10 x64
版本：1.2.5 （之前1.2.4也是一样）
设置：
![image](https://user-images.githubusercontent.com/91249019/200215891-08b56e0a-5105-4042-993e-1d2c772c0eda.png)

聊天界面：
![image](https://user-images.githubusercontent.com/91249019/200215980-08e786e3-604d-4908-8538-3c63ff4ab1a9.png)

已经尝试清屏，还是一样卡
尝试删除消息屏蔽之后，才正常。

不知道是否我的使用方式不正确

此外：消息提示似乎也不起作用..

**Comment by imlinhanchao** [comment]
消息提示要再勾选下面的提示方式。

**Comment by imlinhanchao** [comment]
测试了一下屏蔽，首次加载因为要对每条消息运算一次所有正则，会卡住 1 秒。后面感觉还好呀~
