### ISSUE TITLE
帖子看不到打赏区，无法打赏

### ISSUE THREAD

**Issue by KwdeTfpv** [imlinhanchao/fishpi-desktop#35]
去web打赏了也看不到

**Comment by imlinhanchao** [comment]
当然~因为，没有做，评论也只能看到第一页 <img src=https://github.com/imlinhanchao/fishpi-desktop/assets/1502581/da0ed68f-8ecc-4f09-93c8-3c07556fb043 width=20 align=bottom/>

**Comment by imlinhanchao** [comment]
已解决，待发布
