### ISSUE TITLE
私聊不存的用户会弹出报错

### ISSUE THREAD

**Issue by TwoCarPongPong** [imlinhanchao/fishpi-desktop#43]
![屏幕截图(3)](https://github.com/imlinhanchao/fishpi-desktop/assets/52689679/d5726d9b-2906-485c-99a7-61e543dedbaf)
![屏幕截图(4)](https://github.com/imlinhanchao/fishpi-desktop/assets/52689679/4fcc8462-4a1a-4113-ae31-b342ca70007d)

**Comment by imlinhanchao** [comment]
已修正，待发布
